// examples/user-management/react-user-management/src/App.jsx
import { useState, useEffect } from 'react'
import './App.css'
import { openmodels } from './openmodelsClient'
import Auth from './Auth'
import Account from './Account'

function App() {
  const [session, setSession] = useState(null)

  useEffect(() => {
    openmodels.auth.getSession().then(({ data: { session } }) => {
      setSession(session)
    })

    openmodels.auth.onAuthStateChange((_event, session) => {
      setSession(session)
    })
  }, [])

  return (
    <div className="container" style={{ padding: '50px 0 100px 0' }}>
      {!session ? <Auth /> : <Account key={session.user.id} session={session} />}
    </div>
  )
}

export default App

// examples/user-management/solid-user-management/src/App.tsx
import { Component, createEffect, createSignal } from 'solid-js'
import { openmodels } from './openmodelsClient'
import { AuthSession } from '@supabase/supabase-js'
import Account from './Account'
import Auth from './Auth'

const App: Component = () => {
	const [session, setSession] = createSignal<AuthSession | null>(null)

	createEffect(() => {
		openmodels.auth.getSession().then(({ data: { session } }) => {
			setSession(session)
		})

		openmodels.auth.onAuthStateChange((_event, session) => {
			setSession(session)
		})
	})

	return (
		<div class="container" style={{ padding: '50px 0 100px 0' }}>
			{!session() ? <Auth /> : <Account session={session()!} />}
		</div>
	)
}

export default App
